### ISSUE TITLE
behance ne yapacak 

### ISSUE THREAD

**Issue by Tugcehasakavuk** [dsciztech/behance#2]
Biz ne yapacağız.

**Comment by mehmetoguzderin** [comment]
Behance takımı düzenli olarak Behance içerisindeki gelişmeleri izleyerek kürasyonlar oluşturup DSC IZTECH'e sunacak; böylelikle onlardan esinlenip, çalışmalarımızı bir üst düzeye çıkarabileceğiz. Behance takımının çalışmaları DSC IZTECH için yaşamsal önemde olacak.

**Comment by Tugcehasakavuk** [comment]
Sorumu yanıtladı, teşekkürler.
